export const siteConfig = {
  name: "Sijomon P.S",
  title: "Sijomon P.S | Web Developer & Video Editor",
  description: "A passionate Web Developer & Video Editor crafting beautiful digital experiences.",
  url: "https://sijomonps.dev",
  email: "sijomon700@gmail.com",
  location: "Thiruvalla, Kerala",
  socials: {
    github: "https://github.com/sijomonps",
    linkedin: "https://www.linkedin.com/in/sijomonps/",
    instagram: "https://www.instagram.com/zeejo.ae/",
    twitter: "https://twitter.com/sijomonps",
  },
  stats: {
    projects: "26+",
    contributions: "220+",
    experience: "2+",
  },
};

export const projects = [
  {
    id: 1,
    title: "TEDxKCMT",
    description: "A website built for the TEDxKCMT club's event. Clean design reflecting the TEDx brand with modern aesthetics.",
    longDescription: "This project involved creating a complete website for the TEDxKCMT event, featuring speaker profiles, event schedule, and registration functionality. The design focuses on the iconic TEDx branding while maintaining modern web standards.",
    tags: ["HTML", "CSS", "Responsive"],
    github: "https://github.com/sijomonps/Tedxkcmt",
    live: null,
    emoji: "🎤",
    color: "from-red-500 to-orange-500",
    category: "web",
    featured: true,
  },
  {
    id: 2,
    title: "Handmade Crafts Shop",
    description: "A responsive e-commerce website for handmade crafts with product listings and mobile-friendly design.",
    longDescription: "An e-commerce platform designed for artisans to showcase and sell handmade crafts. Features include product categories, search functionality, and a fully responsive design that works seamlessly on all devices.",
    tags: ["HTML", "CSS", "Bootstrap"],
    github: "https://github.com/sijomonps/Shopping-Website-for-my-Friend",
    live: null,
    emoji: "🛍️",
    color: "from-pink-500 to-rose-500",
    category: "web",
    featured: true,
  },
  {
    id: 3,
    title: "Idea2Patent",
    description: "A web application focused on innovation and patent ideas with modern UI.",
    longDescription: "A platform that helps innovators document and develop their ideas into patentable concepts. Features include idea submission, patent search, and collaboration tools.",
    tags: ["CSS", "Web App"],
    github: "https://github.com/sijomonps/Idea2Patent",
    live: null,
    emoji: "💡",
    color: "from-yellow-500 to-amber-500",
    category: "web",
    featured: true,
  },
  {
    id: 4,
    title: "Library Management",
    description: "A library management system with intuitive interface for managing books and users.",
    longDescription: "Complete library management solution with features for book cataloging, user management, borrowing/returning books, and generating reports.",
    tags: ["CSS", "Management System"],
    github: "https://github.com/sijomonps/Library-Managament",
    live: null,
    emoji: "📚",
    color: "from-blue-500 to-indigo-500",
    category: "web",
    featured: true,
  },
  {
    id: 5,
    title: "CYDATA Event",
    description: "Event website with modern design and smooth user experience.",
    longDescription: "A dynamic event website built for CYDATA featuring event information, speaker profiles, registration system, and interactive schedule.",
    tags: ["CSS", "Event Website"],
    github: "https://github.com/sijomonps/CYDATA_event",
    live: null,
    emoji: "🎯",
    color: "from-green-500 to-emerald-500",
    category: "web",
    featured: false,
  },
  {
    id: 6,
    title: "Insight Stickers",
    description: "Creative project featuring insights and visual content.",
    longDescription: "A creative web project showcasing data insights through interactive visual elements and engaging design patterns.",
    tags: ["CSS", "Creative"],
    github: "https://github.com/sijomonps/insightstikers",
    live: null,
    emoji: "📊",
    color: "from-purple-500 to-violet-500",
    category: "creative",
    featured: false,
  },
];

export const skills = {
  frontend: ["HTML5", "CSS3", "JavaScript", "React", "Next.js", "Tailwind CSS", "Bootstrap"],
  tools: ["Git", "GitHub", "VS Code", "Figma", "Vercel", "npm"],
  video: ["Premiere Pro", "After Effects", "DaVinci Resolve", "Motion Graphics", "Color Grading"],
  learning: ["TypeScript", "Node.js", "Python", "MongoDB", "PostgreSQL"],
};

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About" },
  { href: "/projects", label: "Projects" },
  { href: "/contact", label: "Contact" },
];
